PUT http://10.212.1.4:1401/qrcode HTTP/1.1
content-type: application/json

{
  "barcode": "2919207900000397",
  "date_p": "2023-05-04 12:25:49",
  "date": "2023-05-04T09:25:49.099Z",
  "index": "344964",
  "typeBag": 1,
  "attrBag": 4,
  "typeTara": 3,
  "model": 3,
  "sizeMailType": 5,
  "sizeMailCtg": 3,
  "sizeMailRank": 2,
  "sizeTransType": 2,
  "sizeWeight": 15,
  "sizePostMark": 24,
  "sizeValue": 13,
  "sizePayment": 13,
  "itemsCount": 9,
  "pagesCount": 1,
  "pageItems": 9,
  "pageNumber": 1,
  "qrPosition": 0,
  "rpis_groups": [
    {
      "mail_type": 2,
      "cnt": 4
    },
    {
      "mail_type": 4,
      "cnt": 4
    },
    {
      "mail_type": 23,
      "cnt": 1
    }
  ],
  "items": [
    {
      "RpiBarcode": "80092283151919",
      "Weight": 10270,
      "MailType": 23,
      "MailCtg": 2,
      "MailRank": 0,
      "PostMark": 8388608,
      "TransType": 1,
      "IndexFrom": "603961",
      "IndexTo": "294540",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 1,
        "isPodNumber": 0
      },
      "RpiValue": 381000
    },
    {
      "RpiBarcode": "80111283824385",
      "Weight": 1081,
      "MailType": 4,
      "MailCtg": 3,
      "MailRank": 0,
      "PostMark": 2048,
      "TransType": 1,
      "IndexFrom": "347900",
      "IndexTo": "294703",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    },
    {
      "RpiBarcode": "80110783080819",
      "Weight": 2145,
      "MailType": 4,
      "MailCtg": 3,
      "MailRank": 0,
      "PostMark": 2048,
      "TransType": 1,
      "IndexFrom": "115573",
      "IndexTo": "294694",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    },
    {
      "RpiBarcode": "91011000694498",
      "Weight": 11,
      "MailType": 2,
      "MailCtg": 1,
      "MailRank": 0,
      "PostMark": 0,
      "TransType": 1,
      "IndexFrom": "294501",
      "IndexTo": "294517",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    },
    {
      "RpiBarcode": "91011000694535",
      "Weight": 11,
      "MailType": 2,
      "MailCtg": 1,
      "MailRank": 0,
      "PostMark": 0,
      "TransType": 1,
      "IndexFrom": "291011",
      "IndexTo": "294650",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    },
    {
      "RpiBarcode": "91057000347729",
      "Weight": 12940,
      "MailType": 4,
      "MailCtg": 3,
      "MailRank": 0,
      "PostMark": 0,
      "TransType": 1,
      "IndexFrom": "291057",
      "IndexTo": "294562",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    },
    {
      "RpiBarcode": "91011000694610",
      "Weight": 15,
      "MailType": 2,
      "MailCtg": 1,
      "MailRank": 0,
      "PostMark": 0,
      "TransType": 1,
      "IndexFrom": "291011",
      "IndexTo": "294005",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    },
    {
      "RpiBarcode": "94325000028465",
      "Weight": 46,
      "MailType": 2,
      "MailCtg": 1,
      "MailRank": 0,
      "PostMark": 0,
      "TransType": 1,
      "IndexFrom": "294325",
      "IndexTo": "200000",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    },
    {
      "RpiBarcode": "91057000347736",
      "Weight": 12600,
      "MailType": 4,
      "MailCtg": 3,
      "MailRank": 0,
      "PostMark": -1,
      "TransType": 1,
      "IndexFrom": "291057",
      "IndexTo": "294562",
      "characteristic": {
        "bType": 0,
        "attachType": 0,
        "isReturnSender": 0,
        "isPayment": 0,
        "isValue": 0,
        "isPodNumber": 0
      }
    }
  ]
}