import { Form23AInterface } from '../../@generated/interfaces/form23a.interface'

export const form23aProps: Form23AInterface = {
	dataMatrixBase64: 'adwa',
	barcodeBase64: 'adawd',
	maintainer: 'дядя Вася',
	form_81: '222',
	seal_number: '0202',
	vechicle_number: 'вв 0101 вв',
	transporter: 'ЛугТранс',
	invoice_number: '344962 79 1005659 8',
	outcome_mail_index: '344962 79 1005659 8',
	income_mail_index: '291920',
	income_mail_adress: 'ЛУГАНСК ЦОПП',
	postal_capacity_index: '344962 79 1005660 4',
	noc: {
		from_first_kilogram_departure: '0',
		ems: '0',
		government: '0',
		international: '0',
		insurance: '0',
		from_registered_correspondence: '0',
		with_simple_correspondence: '0',
		weight: '0.309',
		with_stamp: '0',
		empty_containers: '0',
		registered_mail_group: '0',
	},
	total_capacities: '1',
	total_registered_mail_sent_openly: '1',
	noc_sum: {
		from_first_kilogram_departure: '0',
		ems: '0',
		government: '0',
		international: '0',
		insurance: '0',
		from_registered_correspondence: '0',
		with_simple_correspondence: '0',
		weight: '0.309',
		with_stamp: '0',
		empty_containers: '0',
		registered_mail_group: '0',
	},
	total_capacities_sum: '1',
	total_registered_mail_sent_openly_sum: '1',
}
