version: "3.8"

services:
  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: "host"
    container_name: api-${ENV_MODE}
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile.app.${ENV_MODE}
    ports:
      - 85:5055
      - 5172:5172
    env_file:
      - ../configs/.env
    tty: true
    stdin_open: true
    restart: on-failure

  # identity-api:
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   # network_mode: "host"
  #   container_name: identity-api-${ENV_MODE}
  #   build:
  #     context: ../app/workspaces/identity
  #     dockerfile: ./docker/Dockerfile.identity.${ENV_MODE}
  #   # ports:
  #   #   - 85:5055
  #   #   - 5172:5172
  #   env_file:
  #     - ../configs/.env
  #   tty: true
  #   stdin_open: true
  #   restart: on-failure

  redis:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: "host"
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /db/redis/data:/data
    tty: true
    stdin_open: true
    restart: on-failure
