PUT http://10.212.1.4:1401/qrcode HTTP/1.1
content-type: application/json

 {"form" : {
				"barcode": 2919200100000040,
				"index": 346942,
				"date": "2023-02-16T15:33:24.000Z",
				"typeBag": 5,
				"attrBag": 11,
				"typeTara": 0,
				"model": 0,
				"sizeMailType": 6,
				"sizeMailCtg": 4,
				"sizeMailRank": 4,
				"sizeTransType": 3,
				"sizeWeight": 15,
				"sizePostMark": 16,
				"sizeValue": 25,
				"sizePayment": 25,
				"itemsCount": 26,
				"pagesCount": 1,
				"pageItems": 26,
				"pageNumber": 1,
				"qrPosition": 0,
				"items": [
					{
						"RpiBarcode": "29100107000295",
						"Weight": 2123,
						"MailType": 4,
						"MailCtg": 3,
						"PostMark": 0,
						"IndexFrom": 291001,
						"TransType": 1,
						"MailRank": 0,
						"IndexTo": 346330,
						"characteristic": {
							"bType": 0,
							"attachType": 0,
							"isReturnSender": 0,
							"isPayment": 0,
							"isValue": 0,
							"isPodNumber": 0
						}
					}
				]
			}
 }